global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "bootstrap-peer"
    static_configs:
      - targets: ["bootstrap-peer:8000"]

  - job_name: "replication-servers"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        regex: "replication-server"
        action: keep
      - source_labels: [__address__]
        regex: "(.*):.*"
        target_label: __address__
        replacement: "$1:8000"
