name: CI
on: [push, workflow_dispatch]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install
        shell: bash

      - name: Run eslint
        run: pnpm run lint

  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      # - name: Run @canvas-js/gossiplog tests
      #   run: pnpm --filter @canvas-js/gossiplog test

      - name: Run @canvas-js/modeldb tests
        run: pnpm --filter @canvas-js/modeldb test

      - name: Run @canvas-js/core tests
        run: pnpm --filter @canvas-js/core test

      - name: Run @canvas-js/vm tests
        run: pnpm --filter @canvas-js/vm test

      - name: Run @canvas-js/interfaces interface tests
        run: pnpm --filter @canvas-js/interfaces test
